### ISSUE TITLE
Hello, can you add one

### ISSUE THREAD

**Issue by 39968** [FaultyFunctions/SoulGraves#1]
Configuration files such as
Only I can pick it up before it breaks.
Or the control of time

**Comment by 39968** [comment]
To get the stuff back, only the player who died can break its headstone

**Comment by FaultyFunctions** [comment]
These are on my todo list but not sure when I'll get to it. Hopefully soon, thanks for submitting this!

**Comment by FaultyFunctions** [comment]
@39968 Hello! This has now been implemented along with a bunch of other options. You can download the new version here: https://modrinth.com/plugin/soul-graves/version/1.0.0
