### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by MjKey** [FaultyFunctions/SoulGraves#2]
Make a parameter in the config so that the souls do not disappear at all

**Comment by FaultyFunctions** [comment]
Well you can set the time in the config to a really high number as a workaround right now, but do you really want them to last *forever*? I feel like that would have performance implications over time if people don't collect their souls.

**Comment by MjKey** [comment]
Хорошо, вы правы, но иногда игрок или выходит и не успевает за душой и забрать свои вещи или ещё что-то бывает происходит, как вариант реализовать - Если игрок вышел с сервера, то душа его пропадает, пока он вновь не зайдёт на сервер и там уже отсчёт времени пока душа существует - продолжится.

**Comment by FaultyFunctions** [comment]
Hmm would a better option be to have a `owner-offline-freeze-timer` config option so the timer only ticks down if the owner of the soul is online? Would that work for you?

**Comment by MjKey** [comment]
I think yes, that would be good

**Comment by FaultyFunctions** [comment]
Okay `offline-owner-timer-freeze` is now implemented and available in version 1.2.0.
