### ISSUE TITLE
[Bug] Soul picked up in spectator mode

### ISSUE THREAD

**Issue by darksaid98** [FaultyFunctions/SoulGraves#4]
I have a system that keeps the player spectating at their death position for a few seconds before they respawn. This led to an issue where players instantly picked up their souls after dying.

The simplest fix I suspect, would be preventing players in spectator mode from picking up souls.

**Comment by FaultyFunctions** [comment]
Thanks for pointing this out! It's now been fixed and available in version 1.1.1.
